name: ci-testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install package and pytest
        run: |
          python -m pip install .
          python -m pip install pytest

      - name: Run unit tests
        run: pytest -v
